POST http://localhost:3003/blogs
Content-Type: application/json

{
    "title": "How  JS",
    "author": "BiBags",
    "url": "bigags.com",
    "likes": 99
}

###

GET http://localhost:3003/blogs

###

GET http://localhost:3003/blogs/6193886d5560ec1c7f0c52c2

###
DELETE http://localhost:3003/blogs/61939ba00fd8ae45e3525163