POST http://localhost:3003/users
Content-Type: application/json

{
    "blogs": [],
    "username": "third",
    "name": "third",
    "password": "third",
    "user":"third?"
}

###

GET http://localhost:3003/users