POST http://localhost:3003/users
Content-Type: application/json

{
    "blogs": [],
    "username": "fourth",
    "name": "fourth",
    "password": "fourth",
    "user":"fourth?"
}

###

GET http://localhost:3003/users